// gen-ts-kinds generates a TypeScript ClarificationKindValue union type from the
// Go clarificationkind package. Run via: make generate-kinds
package main

import (
	"fmt"
	"os"
	"sort"

	"github.com/casebrophy/planner/business/types/clarificationkind"
)

func main() {
	if len(os.Args) < 2 {
		fmt.Fprintln(os.Stderr, "usage: gen-ts-kinds <output-file>")
		os.Exit(1)
	}

	// Collect all kind string values from KindWeights (exported, exhaustive).
	values := make([]string, 0, len(clarificationkind.KindWeights))
	for k := range clarificationkind.KindWeights {
		values = append(values, k.String())
	}
	sort.Strings(values)

	f, err := os.Create(os.Args[1])
	if err != nil {
		fmt.Fprintln(os.Stderr, err)
		os.Exit(1)
	}
	defer f.Close()

	fmt.Fprintln(f, "// Code generated by api/tooling/gen-ts-kinds. DO NOT EDIT.")
	fmt.Fprintln(f, "// Source of truth: business/types/clarificationkind/clarificationkind.go")
	fmt.Fprintln(f, "")
	fmt.Fprint(f, "export type ClarificationKindValue =")
	for _, v := range values {
		fmt.Fprintf(f, "\n  | %q", v)
	}
	fmt.Fprintln(f, "")
}
